require('impatient')
require('config')
require('settings')
require('colorscheme')
require('plugins')
require('keymappings')
require('functions')

require('lsp/config')
require('lsp/bash')
require('lsp/css')
require('lsp/graphql')
require('lsp/html')
require('lsp/json')
require('lsp/lua')
require('lsp/tsserver')
