require('impatient') -- This needs to be first
require('config')
require('settings')
require('colorscheme')
require('plugins')
require('keymappings')
require('autocmds')
require('functions')

require('lsp.config')
require('lsp.servers.bash')
require('lsp.servers.css')
require('lsp.servers.graphql')
require('lsp.servers.html')
require('lsp.servers.json')
require('lsp.servers.lua')
require('lsp.servers.tsserver')
require('lsp.servers.tailwind')
