require('settings')

require('plugins/telescope')
require('plugins/colorizer')
require('plugins/gitsigns')
require('plugins/treesitter')
require('plugins/compe')
require('plugins/tree')
require('plugins/kind')
require('plugins/saga')
require('plugins/autopairs')
require('plugins/rnvimr')
require('plugins/kommentary')
require('plugins/numb')
require('plugins/trouble')
require('plugins/signature')

require('lsp/install')
require('lsp/config')
require('lsp/efm')
require('lsp/tsserver')
require('lsp/graphql')
require('lsp/html')
require('lsp/css')
require('lsp/lua')
