require('plugins/telescope')
require('plugins/colorizer')
require('plugins/gitsigns')
require('plugins/treesitter')
require('plugins/compe')
require('plugins/tree')
require('plugins/lightbulb')
require('plugins/kind')
require('plugins/saga')

require('lsp/config')
require('lsp/efm')
require('lsp/tsserver')
require('lsp/graphql')
require('lsp/html')
